version: '2'
services:
  dev-nginx:
    build:
      context: ./.docker/dev/nginx
    container_name: dev-nginx
    links:
      - dev-api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/dist:/usr/share/nginx/html
  dev-web:
    build:
      context: ./.docker/dev/webpack
    container_name: dev-web
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: "npm run serve"
  dev-api:
    build:
      context: ./.docker/dev/node
    container_name: dev-api
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: "npm run dev"
